// script.js
document.addEventListener('DOMContentLoaded', function() {
    var compliments = ["Roisin, you're incredibly intelligent and creative!",
    "Your dedication to becoming a technology and design teacher is inspiring.",
    "Roisin, you have a fantastic sense of design and aesthetics.",
    "Your passion for learning and teaching is truly admirable.",
    "Roisin, you're destined for success in your tech and design journey!",
    "Roisin, you're incredibly talented with a saw, crafting masterpieces effortlessly.",
    "Rolo, your skill with tools is unmatched; you transform every project into a work of art.",
    "Roisin, your precision in creating 3D printed models is truly impressive, showcasing your attention to detail.",
    "Rolo, your woodworking skills are outstanding, turning raw materials into beautiful creations.",
    "Roisin, you're a maestro with circuit boards, bringing technology to life with your expertise.",
    "Rolo, your ability to work with tools is like a symphony, harmonizing each element into perfection.",
    "Roisin, your 3D printed models reflect not just creativity but a true passion for innovation.",
    "Rolo, your woodworking finesse turns simple materials into pieces of functional art.",
    "Roisin, your command over circuit boards is nothing short of extraordinary; you bring ideas to reality seamlessly.",
    "Rolo, your hands-on skills with a saw are unmatched, turning any piece of wood into a masterpiece.",
    "Roisin, your expertise in using tools makes every project you undertake a testament to your craftsmanship.",
    "Rolo, your 3D printed creations are not just objects; they're expressions of your boundless creativity.",
    "Roisin, your woodwork is a blend of skill and artistry, creating pieces that tell a story.",
    "Rolo, your mastery over circuit boards is like magic, bringing circuits to life with every connection.",
    "Roisin, the way you handle a saw is like watching an artist sculpt; your precision is admirable.",
    "Rolo, your use of tools is more than just a skill; it's a form of artistic expression.",
    "Roisin, your 3D printed models showcase your ability to turn ideas into tangible, innovative realities.",
    "Rolo, your woodworking craftsmanship is a testament to your dedication and passion for the craft.",
    "Roisin, your expertise with circuit boards is like composing a symphony of electrons, creating harmony in technology.",
    "Rolo, the way you handle a saw is not just skilled; it's an art form, creating beauty with every cut.",
    "Roisin, your woodworking finesse turns simple materials into pieces of functional art.",
    "Rolo, your command over circuit boards is nothing short of extraordinary; you bring ideas to reality seamlessly.",
    "Roisin, your expertise in using tools makes every project you undertake a testament to your craftsmanship.",
    "Rolo, your 3D printed creations are not just objects; they're expressions of your boundless creativity.",
    "Roisin, your woodwork is a blend of skill and artistry, creating pieces that tell a story.",
    "Rolo, your mastery over circuit boards is like magic, bringing circuits to life with every connection.",
    "Roisin, the way you handle a saw is like watching an artist sculpt; your precision is admirable.",
    "Rolo, your use of tools is more than just a skill; it's a form of artistic expression.",
    "Roisin, your 3D printed models showcase your ability to turn ideas into tangible, innovative realities.",
    "Rolo, your woodworking craftsmanship is a testament to your dedication and passion for the craft.",
    "Roisin, your expertise with circuit boards is like composing a symphony of electrons, creating harmony in technology.",
    "Rolo, the way you handle a saw is not just skilled; it's an art form, creating beauty with every cut.",
    "Roisin, your perseverance and hard work will lead to great achievements.",
    "You're not just studying to be a teacher, Roisin; you're shaping the future of technology and design education!",
    "In your current placement, Roisin, your ability to convey complex technological concepts is truly impressive, making the material accessible and engaging for students.",
    "Rolo, your passion for teaching technology shines through during your current placement, creating a positive and dynamic classroom environment.",
    "Roisin, you foster an inclusive and encouraging learning atmosphere during your placement, ensuring that every student feels valued and supported in the technology class.",
    "Rolo, your hands-on approach to teaching technology demonstrates a practical understanding of pedagogical techniques, preparing students for real-world applications.",
    "In your current placement, Roisin, your commitment to staying updated on the latest tech trends enriches the learning experience for students, keeping them informed and engaged.",
    "Rolo, you excel at cultivating a love for learning and problem-solving among students during your placement, fostering their curiosity and critical thinking skills.",
    "Roisin, your creativity in designing technology lessons during your current placement makes the material interesting and memorable for all students.",
    "Rolo, the way you balance theory and practical application in teaching technology showcases a comprehensive understanding of effective teaching methods during your placement.",
    "During your current placement, Roisin, your dedication to fostering curiosity and exploration in your technology class shapes the future innovators of the tech world.",
    "Rolo, your personalized approach to teaching technology accommodates diverse learning styles during your placement, allowing each student to thrive and participate actively.",
    "Roisin, you demonstrate a knack for adapting educational content and demystifying complex coding languages, making programming accessible and enjoyable for your students during your placement.",
    "In your current placement, Rolo, your enthusiasm for creating an inclusive learning environment is contagious, creating an atmosphere of excitement and eagerness to learn.",
    "Roisin, you skillfully integrate real-world examples and practical experiences into your technology lessons during your placement, enhancing the understanding of tech concepts.",
    "Rolo, your support and encouragement empower students to take an active role in their technology education during your placement, fostering a positive and collaborative classroom culture.",
    "During your current placement, Roisin, your commitment to fostering collaboration and communication skills among technology students is crucial for their future success in the tech industry.",
    "Rolo, you provide a nurturing environment during your placement, allowing technology students to learn from their mistakes and encouraging resilience and perseverance.",
    "In your current placement, Roisin, your adaptability in tailoring your teaching methods to cater to different learning styles ensures that every technology student has the opportunity to succeed.",
    "Rolo, your emphasis on instilling a sense of responsibility and ethical consideration in technology students during your placement prepares them for the ethical challenges of the tech world.",
    "Roisin, your mentorship during your placement extends beyond the technology classroom, guiding students in exploring their individual interests and potential career paths within the tech field.",
    "During your current placement, Rolo, your dedication to fostering a love for learning in technology creates a lasting impact on students, laying the foundation for their future success in the tech industry.",
    "Roisin, your sense of style is effortlessly cool, always reflecting your authentic self.",
    "Rolo, you've got a laid-back charm that makes your appearance genuine and relatable.",
    "Roisin, your smile is infectious, and it lights up any room you walk into.",
    "Rolo, your positive energy is so down-to-earth; it brings good vibes wherever you go.",
    "Roisin, your confidence is real and natural, making you stand out in the best way.",
    "Rolo, your fashion choices are on point, and they really showcase your personality.",
    "Roisin, you've got a natural grace about you that makes everything seem effortless.",
    "Rolo, your authenticity is what sets you apart, and it's so refreshing.",
    "Roisin, your self-care game is strong, and it clearly contributes to your overall well-being.",
    "Rolo, you've got this magnetic personality that draws people in , it's just who you are.",
    "Roisin, your choice of accessories always adds that perfect touch to your look.",
    "Rolo, your posture and the way you carry yourself show a quiet confidence that's really cool.",
    "Roisin, your positive mindset and the way you treat yourself are truly empowering.",
    "Rolo, your style is unique and cool, and it definitely reflects your personality.",
    "Roisin, you've got a charm that's down-to-earth and relatable; it's what makes you so likable.",
    "Rolo, your fashion sense is a great blend of comfort and style, and it suits you perfectly.",
    "Roisin, your self-assurance is real and not showy, and it makes you all the more appealing.",
    "Rolo, your beauty is more than skin deep; it comes from your kindness and warmth.",
    "Roisin, your presence is a reminder of your individuality, and that's what makes you interesting.",
    "Rolo, your smile isn't just about looking good; it genuinely shows the joy you carry inside.",
    "Roisin, your style mirrors your personality , vibrant and dynamic in the best way.",
    "Rolo, your features tell a story, and that's what makes you uniquely beautiful.",
    "Roisin, your self-confidence is admirable, and it's something others can learn from.",
    "Rolo, you radiate positivity, and that's what truly makes you beautiful inside and out.",
    "Roisin, your self-love is evident, and it's something to be celebrated.",
    "Rolo, your presence is warm and welcoming, making everyone around you feel at ease.",
    "Roisin, your beauty is not about following trends; it's about being authentically you.",
    "Rolo, your down-to-earth charm is magnetic, making you stand out in the best way.",
    "Roisin, you're just naturally pretty, and it's awesome.",
    "Rolo, you've got this sweet and genuine beauty that's hard to miss.",
    "Roisin, your features are so pretty, and they light up your whole look.",
    "Rolo, you're genuinely sweet, and it shows in how pretty you are.",
    "Roisin, you're pretty in this effortless and lovely way.",
    "Rolo, your presence is just so pretty, it brightens up any room.",
    "Roisin, your beauty is not just on the surface; it's this sweet vibe you carry.",
    "Rolo, your look is so pretty and so naturally you , it's perfect.",
    "Roisin, that smile of yours adds this extra touch of pretty to everything.",
    "Rolo, your beauty is magnetic; people can't help but notice how pretty you are.",
    "Roisin, you've got this elegant and pretty thing going on that's so charming.",
    "Rolo, your beauty is subtly pretty, and it leaves a lasting impression.",
    "Roisin, your charm and pretty features make you stand out in such a lovely way.",
    "Rolo, your sweet nature adds to your overall pretty and captivating presence.",
    "Roisin, your natural glow makes you look pretty and radiant.",
    "Rolo, your beauty is just so effortlessly pretty, and it suits you perfectly.",
    "Roisin, your features work together in this really pretty harmony.",
    "Rolo, your whole look is just casually pretty, and it's fantastic.",
    "Roisin, those eyes of yours make your entire face look extra pretty.",
    "Rolo, you're pretty in this easygoing and genuine way, and it's wonderful.",
    "Roisin, your pretty smile and warmth make everyone feel good around you.",
    "Rolo, your beauty is more than just looks; it's in how sweet you are.",
    "Roisin, your smile is pretty infectious, and it makes everything brighter.",
    "Rolo, your whole vibe is just pretty, and it's a pleasure to be around.",
    "Roisin, your beauty is so naturally pretty, and it's something special.",
    "Rolo, your sweet personality adds to your overall pretty appearance.",
    "Roisin, your beauty is the kind that just makes people smile.",
    "Rolo, your pretty and genuine nature is something that people really appreciate.",
    "Hey Roisin, may your creativity flow through Strabane's streets like the River Mourne and your designs be as resilient as the town's spirit!",
    "Rolo, in the world of woodwork, remember: Measure twice, cut once, and blame any mishaps on the Strabane leprechauns , they're known for mischief.",
    "Roisin, may your technology never glitch, your saw always be as sharp as Strabane wit, and your coffee always strong , the Strabane trifecta of productivity!",
    "Hey Rolo, in the workshop of life, be the craftsman, not the splinter. Unless, of course, it's a Strabane splinter, in which case, wear it with pride.",
    "Roisin, keep your code as tidy as Strabane's streets, your cuts as precise as a Strabane craic, and your Irish wit sharper than the Sperrin Mountains.",
    "Rolo, in the grand dance of design, may your steps be as nimble as a Strabane jig, and your creations as awe-inspiring as the beauty of the town.",
    "Roisin, they say measure twice, cut once. But if you're in Strabane, you might add a step: have a cup of tea at Granny Annie's and contemplate the meaning of life in between.",
    "Hey Rolo, in the world of woodwork, life's too short to use dull tools or to write inefficient code. Keep both sharp, and may the spirit of Strabane be with you!",
    "Roisin, in the workshop of life, be the craftswoman, not the splinter. Unless, of course, it's a Strabane splinter, in which case, wear it with pride.",
    "Rolo, keep your code as tidy as Strabane's streets, your cuts as precise as a Strabane craic, and your Irish wit sharper than the Sperrin Mountains.",
    "Hey Roisin, in the grand dance of design, may your steps be as nimble as a Strabane jig, and your creations as awe-inspiring as the beauty of the town.",
    "Rolo, they say measure twice, cut once. But if you're in Strabane, you might add a step: have a cup of tea at Granny Annie's and contemplate the meaning of life in between.",
    "Roisin, in the world of woodwork, life's too short to use dull tools or to write inefficient code. Keep both sharp, and may the spirit of Strabane be with you!",
    "Hey Rolo, woodwork rule #1: If you can't fix it with a bit of Strabane magic or a good Irish blessing, it's probably not worth fixing.",
    "Roisin, may your circuits be as organized as the Strabane summer festival, your sawdust minimal like Strabane's crowds, and your humor as dry as a Strabane summer day.",
    "Rolo, in the kingdom of creation, be the ruler, not the court jester. Unless, of course, you're the jester entertaining the good folks of Strabane.",
    "Hey Roisin, Irish saying: 'May the road rise to meet you.' Strabane's version: 'May your road be as smooth as the Strabane bypass.'",
    "Rolo, when life gives you scrap wood, build a bridge and get over it. The Strabane way of problem-solving!",
    "Roisin, in the dance of technology, always lead with your best moves, and don't be afraid to throw in a Strabane two-step for good measure.",
    "Rolo, they say laughter is the best medicine. In woodworking and design, it's also the best way to cope with any Strabane road diversions.",
    "Hey Roisin, Irish saying: 'May the road rise to meet you.' Strabane's version: 'May your road be as smooth as the Strabane bypass.'",
    "Rolo, in the dance of technology, always lead with your best moves, and don't be afraid to throw in a Strabane two-step for good measure.",
    "Roisin, they say laughter is the best medicine. In woodworking and design, it's also the best way to cope with any Strabane road diversions.",
    "Hey Rolo, woodwork wisdom: There are no mistakes, only unexpected design features. Just like a Strabane road with a few twists and turns.",
    "Hey Roisin, may your circuits be as intricate as a Celtic knot and your 3D prints as precise as an Irish dance!",
    "Rolo, in the realm of design, remember: Measure twice, 3D print once, and blame any mishaps on Murphy's Law - an Irish design principle.",
    "Roisin, may your technology never glitch, your circuits be as innovative as the Book of Kells, and your coffee always strong , the Irish trifecta of design productivity!",
    "Hey Rolo, in the workshop of life, be the architect, not the blueprint. Unless, of course, you're designing blueprints, then be both!",
    "Roisin, they say measure twice, 3D print once. But if you're Irish, you might add a step: have a cup of tea and contemplate the beauty of your design in between.",
    "Hey Rolo, in the world of technology, life's too short to use outdated software or to design inefficiently. Keep both updated, and may the luck of the Irish be on your side!",
    "Roisin, in the workshop of life, be the visionary, not the glitch. Unless, of course, you're glitching with style, then go for it!",
    "Rolo, keep your code as elegant as a Ha'penny Bridge and your 3D prints as breathtaking as the Cliffs of Moher.",
    "Hey Roisin, in the grand dance of design, may your steps be as agile as a Riverdance, and your creations as visionary as the Giants Causeway.",
    "Roisin, in the world of technology, life's too short to use outdated software or to design inefficiently. Keep both updated, and may the luck of the Irish be on your side!",
    "Hey Rolo, design rule #1: If you can't fix it with a bit of Irish charm or a good design iteration, it's probably not worth fixing.",
    "Roisin, may your circuits be as organized as a perfectly poured pint of Guinness, your 3D prints as detailed as an illuminated manuscript, and your humor as dry as a Dublin pub.",
    "Rolo, in the kingdom of design, be the visionary, not the error message. Unless, of course, your error messages are as witty as Oscar Wilde's quotes.",
    "Hey Roisin, Irish saying: 'May your code be bug-free.' Designer's edition: 'May your designs be glitch-free.'",
    "Roisin, in the dance of technology, always lead with your best designs, and don't be afraid to throw in a 3D-printed surprise for good measure.",
    "Rolo, they say laughter is the best design feedback. In technology and 3D printing, it's also the best way to cope with unexpected malfunctions.",
    "Hey Roisin, Irish saying: 'May your prototypes be functional.' Designer's edition: 'May your prototypes be revolutionary.'",
    "Rolo, in the dance of technology, always lead with your best designs, and don't be afraid to throw in a 3D-printed surprise for good measure.",
    "Roisin, they say laughter is the best design feedback. In technology and 3D printing, it's also the best way to cope with unexpected malfunctions.",
    "Rolo, in the kingdom of design, be the visionary, not the error message. Unless, of course, your error messages are as witty as Oscar Wilde's quotes.",
    "Hey Roisin, may your prototypes be as groundbreaking as a Dublin sunrise and your design iterations as endless as an Irish folklore tale.",
    "Rolo, remember, in the grand Irish tradition, every design challenge is just an opportunity for a good story , and maybe a pint.",
    "Roisin, design tip: If your creation isn't as cutting-edge as an Irish tech startup, you might need to go back to the drawing board.",
    "Rolo, Irish saying: 'May your code be bug-free.' Designer's edition: 'May your designs be glitch-free.'",
    "Hey Roisin, when life gives you scrap material, 3D print a masterpiece. The Irish way of turning challenges into opportunities!",
    "Roisin, your resilience and grace in handling challenges are truly admirable.",
    "Hey Rolo, your ability to make people feel valued and appreciated is a wonderful gift.",
    "Roisin, your optimism and positive outlook on life are contagious.",
    "Rolo, your strength and courage in facing difficulties are truly inspiring.",
    "Hey Roisin, your creativity and unique perspective make you a true original.",
    "Rolo, your generosity and selflessness make you a treasure to those who know you.",
    "Roisin, your ability to find joy in the little moments is truly special.",
    "Hey Rolo, your passion for making a difference is both admirable and inspiring.",
    "Roisin, your authenticity and genuine nature make you someone people can trust.",
    "Rolo, your kindness and consideration for others make you a true friend.",
    "Hey Roisin, your resilience and positive spirit make you a force to be reckoned with.",
    "Rolo, your ability to bring people together with your warmth and kindness is truly remarkable.",
    "Roisin, your dedication to personal growth and self-improvement is truly inspiring.",
    "Hey Rolo, your ability to handle challenges with grace and poise is truly admirable.",
    "Roisin, your generosity and willingness to lend a helping hand make you a true friend.",
    "Rolo, your positive influence on those around you is something to be celebrated.",
    "Hey Roisin, your compassion and empathy towards others are truly heartwarming.",
    "Rolo, your resilience and determination in pursuing your goals are truly admirable.",
    "Roisin, your authenticity and genuine nature make you someone people can trust.",
    "Hey Rolo, your kindness and consideration for others make you a true friend.",
    "Roisin, your positive energy and infectious laughter make any day brighter.",
    "Rolo, your passion for what you do is evident, and it's truly inspiring.",
    "Hey Roisin, your ability to connect with others on a genuine level is a rare and beautiful gift.",
    "Rolo, your positive impact on those around you is something to be celebrated.",
    "Take a breath, Rolo. Oxygen is free, and so is the brief break from stress!",
    "Amidst the chaos, Roisin, remember: stress spelled backward is desserts. Coincidence? I think not. Treat yourself!",
    "Rolo, let's play a game called 'Stress or Dessert?' Spoiler: The answer is always dessert. Always.",
    "Hey Roisin, stress is like a bad internet connection , no one needs it, and it's best ignored while you enjoy life's WiFi moments!",
    "Rolo, stressing is like trying to solve a jigsaw puzzle with missing pieces. Why bother? Life's too short , let's switch to Sudoku!",
    "In the hustle, Roisin, take a break and remember: stress is just misplaced enthusiasm. Let's channel that energy into something more exciting!",
    "Rolo, stress is like a bad haircut , it grows back, and you can always wear a stylish hat in the meantime. Metaphorically speaking, of course!",
    "Amidst the mayhem, Rolo, stress is like a balloon ,it's more fun when you let it go. Bonus points if you make the 'pfft' sound!",
    "Roisin, stress is like a tangled headphone cord , frustrating, but eventually, you'll figure out the right twists and turns. Until then, dance to the chaos!",
    "Hey Rolo, stress is like a mosquito at a barbecue , annoying, but not worth sacrificing your peace. Grab the mental bug spray and shoo it away!",
    "Roisin, if stress were a currency, you'd be a billionaire by now. Let's cash in on some relaxation instead!",
    "Rolo, stress is like a bad date , you don't have to invite it back for a second one. Time for a breakup!",
    "Hey Roisin, stress is like a flat tire , inconvenient but manageable. Plus, it's a good excuse to take a pit stop and enjoy the scenery!",
    "Rolo, stress is like a sneeze , unpredictable and often unnecessary. Bless you, and let's move on with a smile!",
    "Roisin, stress is like a poorly timed punchline , awkward and not that funny. Let's rewrite the joke and enjoy the comedy of life!",
    "Hey Rolo, stress is like a cat video , entertaining for a moment, but it's best enjoyed in moderation. Opt for the laughter playlist instead!",
    "Roisin, when stress knocks, let humor answer the door. It's the best way to tell stress it's not welcome!",
    "Rolo, stress is like a mosquito at a barbecue , annoying, but not worth sacrificing your peace. Grab the mental bug spray and shoo it away!",
    "Hey Roisin, stress is like a bad date , you don't have to invite it back for a second one. Time for a breakup!",
    "Rolo, stress is like a flat tire , inconvenient but manageable. Plus, it's a good excuse to take a pit stop and enjoy the scenery!",
    "Roisin, stress is like a sneeze , unpredictable and often unnecessary. Bless you, and let's move on with a smile!",
    "Hey Rolo, stress is like a poorly timed punchline , awkward and not that funny. Let's rewrite the joke and enjoy the comedy of life!",
    "Roisin, when stress knocks, let humor answer the door. It's the best way to tell stress it's not welcome!",
    "Rolo, stress is like a cat video , entertaining for a moment, but it's best enjoyed in moderation. Opt for the laughter playlist instead!",
    "Rolo, life is like Lilo & Stitch , unpredictable, occasionally chaotic, but always an adventure worth embracing.",
    "Hey Roisin, approaching challenges is like playing Mario Kart , remember, bananas may slip you up, but the finish line is always within reach!",
    "Rolo, navigating life is like mixing a cocktail , a bit of this, a dash of that, and voila! Your unique blend of awesome is ready to be enjoyed.",
    "In the grand game of life, Roisin, be the Mario Kart racer who confidently yells 'Wahoo!' through every twist and turn.",
    "Hey Rolo, just like Irish Rebel Music, life's journey is a mix of rebellion, rhythm, and a bit of foot-tapping enthusiasm!",
    "Roisin, life's challenges are like Mario Kart power-ups , grab the positive ones, dodge the negative ones, and race toward success!",
    "Hey Rolo, if life throws you lemons, make a cocktail, put on some Irish Rebel Music, and dance through the sour moments!",
    "Roisin, just like a well-mixed cocktail, blend your unique flavors of talent, passion, and humor. The result? A masterpiece!",
    "In the adventure book of life, Roisin, may every plot twist be as amusing as a Mario Kart race with unexpected power-ups and banana peels!",
    "Hey Rolo, life's playlist should include a mix of Irish Rebel Music, catchy tunes, and the sound of your laughter echoing through the highs and lows.",
    "Roisin, just like in Mario Kart, sometimes you'll get hit by a blue shell, but remember, you've got a 'Lakitu' cloud to lift you back up!",
    "Hey Rolo, life's challenges are like cocktail recipes , mix it up, improvise, and enjoy the unexpected surprises along the way.",
    "Roisin, in the game of life, you're the Mario Kart character everyone wants to choose , fun, spirited, and always ready for an adventure!",
    "Hey Rolo, just like in Lilo & Stitch, 'ohana' is your secret weapon. Face challenges with your supportive crew, and victory is guaranteed!",
    "Roisin, if life were a Mario Kart race, you'd be the one zipping through challenges with a trail of laughter and confetti behind you!",
    "Hey Rolo, face each day with the determination of a Mario Kart racer aiming for the gold cup. You've got the skills and the humor to win!",
    "Roisin, life's playlist is incomplete without the rebel beats of Irish music and the cheerful tunes of your laughter. Keep the music playing!",
    "In the grand game of life, Roisin, approach challenges with the strategy of a Mario Kart master , collect power-ups and enjoy the ride!",
    "Hey Rolo, just as Mario Kart levels get trickier, so do life's challenges. Good thing you've got the skills to outsmart both!",
    "Roisin, like a Mario Kart racer aiming for the top spot, aim high, use those boost pads of determination, and enjoy the thrill of success!",
    "Hey Rolo, just like in Lilo & Stitch, sometimes life throws you a curveball. Embrace it, dance to the rhythm, and make it part of your 'ohana' story!",
    "Roisin, if life were a cocktail, you'd be the perfect blend of resilience, humor, and style , the kind everyone wants a sip of!",
    "Hey Rolo, just like in Mario Kart, sometimes you'll take a detour, but the scenic route often leads to the most memorable victories!",
    "Roisin, life's twists and turns are like the unpredictable tracks in Mario Kart , buckle up, laugh through the loops, and enjoy the ride!",
    "Hey Rolo, approach life with the spirit of a Mario Kart racer , full throttle, with the occasional banana peel slip, and always aiming for first place!",
    "Roisin, if life were a cocktail party, you'd be the one everyone wants to be around , mixing laughter, joy, and a splash of adventure!",
    "Hey Rolo, life's playlist should have the rebel beats of Irish music, the catchy tunes of your favorite songs, and the laughter that echoes through every day!",
    "Roisin, just like in Mario Kart, sometimes you'll encounter rainbow roads. Embrace the vibrancy, dodge the obstacles, and enjoy the colorful journey!",
    "Hey Rolo, if life hands you mushrooms, use them to grow and conquer challenges like a Mario Kart racer on a winning streak!",
    "Roisin, just like the best cocktails, life's blend is a mix of sweet and sour moments. Sip on the sweetness, laugh off the sourness, and enjoy the concoction!",
    "Hey Rolo, face each day with the exuberance of a Mario Kart racer crossing the finish line , arms raised, laughter echoing, and victory well-deserved!",
    "Roisin, if life were a Mario Kart race, you'd be the one performing stylish drifts through challenges, leaving behind a trail of positivity!",
    "Hey Rolo, face each day with the confidence of a Mario Kart racer picking up a star , invincible, unstoppable, and ready to conquer anything!",
    "Roisin, life's challenges are like the unexpected items in Mario Kart, embrace the positive ones, dodge the negatives, and enjoy the race!",
    "Hey Rolo, just like a well-mixed cocktail, approach each challenge with a splash of humor, a dash of determination, and a twist of resilience!",
    "Roisin, if life were a Mario Kart race, you'd be the one rocking the course with humor, skill, and a joyous spirit. Keep racing towards your goals!",
    "Hey Rolo, life's journey is a bit like a Mario Kart track , filled with twists, turns, and the occasional banana peel. Race on with laughter!",
    "Roisin, if life were a cocktail, you'd be the one with the perfect mix of charm, resilience, and a splash of humor. Cheers to the fantastic blend that is you!",
    "Hey Rolo, face each challenge with the strategy of a Mario Kart racer , collect the positive power-ups, dodge the obstacles, and speed towards success!",
    "In the magical realm of education, Rolo, you're not just a teacher; you're the magician making learning appear out of thin air and disappear into the minds of students.",
    "Hey Roisin, being a teacher is like conducting a circus of curiosity, where each student is a colorful performer adding their own tricks to the big top of education!",
    "Rolo, you're not just teaching; you're the captain of the curiosity ship sailing through uncharted waters, discovering new islands of knowledge!",
    "Hey Rolo, teaching is not just a job; it's a comedy show where you're the star comedian delivering punchlines that make the audience (students) laugh and learn.",
    "Roisin, being a teacher is like hosting your own game show, where every correct answer is a winning moment and every mistake is a chance to learn and have fun!",
    "In the universe of education, Rolo, you're not just a teacher; you're the intergalactic explorer leading students on a journey to the farthest reaches of knowledge!",
    "Hey Rolo, teaching is not just about standing in front of a class; it's about taking your students on a rollercoaster ride of knowledge, twists, turns, and a lot of excitement!",
    "Roisin, you're not just teaching; you're the architect of the laughter bridge, connecting the shores of curiosity and creating a joyful path to understanding!",
    "Hey Rolo, being a teacher is like starring in your own comedy sketch, where each lesson is a hilarious scene, and every student is a co-star in the laughter-filled script of education!",
    "Roisin, you're not just a teacher; you're the master chef in the kitchen of education, cooking up a feast of knowledge with a dash of humor and a pinch of creativity!",
    "In the grand festival of learning, Rolo, you're not just a spectator; you're the ringmaster, orchestrating the magical moments under the big top of education!",
    "Hey Roisin, teaching is not just about filling minds; it's about sparking joy, curiosity, and a sense of wonder that turns each lesson into a carnival of learning!",
    "Rolo, you're not just teaching; you're the maestro leading the orchestra of understanding, where every student's note contributes to the symphony of knowledge!",
    "Hey Rolo, being a teacher is like starring in your own comedy movie , you're the lead actor delivering lines that make everyone laugh, learn, and love the journey of education!",
    "Roisin, in the world of education, you're not just a teacher; you're the pilot of the laughter plane, flying through the clouds of curiosity and turbulence of learning with a smile!",
    "Hey Rolo, teaching is not just a task; it's a game show where you're the host, the contestants are your students, and every correct answer is a step closer to the grand prize of knowledge!",
    "Roisin, you're not just teaching; you're the conductor of the educational orchestra, guiding each student's instrument of curiosity to create a harmonious melody of learning!",
    "Hey Rolo, today's your canvas , paint it with the colors of joy and achievement!",
    "Roisin, embrace today with a smile; you're the author of your own fantastic story!",
    "Rolo, you've got the power to turn challenges into stepping stones. Let's conquer the day!",
    "Hey Roisin, don't forget to sprinkle a bit of your magic everywhere you go today!",
    "Rolo, the world is your classroom, and every moment is a lesson waiting to be learned.",
    "Roisin, today is your stage , perform with confidence, grace, and a dash of humor!",
    "Rolo, face today's journey with the heart of an adventurer and the spirit of a conqueror!",
    "Hey Roisin, every small step counts. You're making progress, one step at a time!",
    "Rolo, let today be a masterpiece, a canvas filled with achievements and smiles.",
    "Roisin, your potential is limitless , let today be a testament to your incredible capabilities!",
    "Rolo, you've got a ticket to a day filled with opportunities. All aboard for success!",
    "Hey Roisin, the day is like clay in your hands. Mold it into something amazing!",
    "Rolo, remember, you're not just going through the day; you're growing through it!",
    "Roisin, be the architect of your day, designing moments that bring joy and fulfillment.",
    "Rolo, seize the day like a treasure hunter seeking gems of positivity and success!",
    "Hey Roisin, today is your runway , walk it with confidence and let success be your style!",
    "Rolo, you've got the tools; now let's build a day full of achievement and happiness!",
    "Roisin, each moment is a chance to shine. Today, let your light illuminate every path!",
    "Rolo, today is not just another day; it's a new opportunity to make a difference!",
    "Hey Roisin, your journey is a story; make today's chapter one worth remembering!",
    "Rolo, wake up and be awesome today! You've got the power to make it extraordinary.",
    "Roisin, today's menu: positivity, productivity, and a dash of laughter!",
    "Rolo, you're the director of your day , cue the success, action, and smiles!",
    "Hey Roisin, let today be a dance of achievements, twirling through challenges with grace!",
    "Rolo, the world is your canvas; paint it with the vibrant colors of your positive energy!",
    "Roisin, each moment is a gift. Unwrap it with gratitude and make the most of today!",
    "Rolo, today is a melody; let your actions compose a beautiful symphony of success!",
    "Hey Roisin, your journey is unique, and today's steps are the notes in your melody of progress!",
    "Rolo, your positive vibes are like sunshine , let them brighten everyone's day!",
    "Roisin, today's script is in your hands. Write a story that fills you with pride!",
    "Rolo, today is not just a day; it's an opportunity to turn dreams into reality!",
    "Rolo, your kindness shines brighter than any star.",
    "Hey Roisin, your intelligence is truly captivating.",
    "Rolo, your talent is a masterpiece in the making.",
    "Hey Roisin, your beauty is simply radiant.",
    "Rolo, your kindness is a beacon of light.",
    "Hey Roisin, your intelligence is a guiding force.",
    "Rolo, your talent is a gift that keeps on giving.",
    "Hey Roisin, your beauty is both inside and out.",
    "Rolo, your kindness makes the world a better place.",
    "Hey Roisin, your intelligence is a source of inspiration.",
    "Rolo, your talent is a unique and wonderful blessing.",
    "Hey Roisin, your beauty is a reflection of your beautiful soul.",
    "Rolo, your kindness is like a warm and comforting embrace.",
    "Hey Roisin, your intelligence is the key to many doors.",
    "Rolo, your talent adds a special touch to everything you do.",
    "Hey Roisin, your beauty is a timeless and captivating charm.",
    "Rolo, your kindness is a gift that keeps on giving.",
    "Hey Roisin, your intelligence is a beacon of wisdom.",
    "Rolo, your talent is a true marvel.",
    "Hey Roisin, your beauty is both captivating and enchanting.",
    "Rolo, you're kind and wonderful.",
    "Hey Roisin, you're really smart!",
    "Rolo, your talent is amazing.",
    "Hey Roisin, you're so pretty!",
    "Rolo, your kindness is heartwarming.",
    "Hey Roisin, you're super smart.",
    "Rolo, your talent is incredible!",
    "Hey Roisin, you're truly beautiful.",
    "Rolo, your kindness is a blessing.",
    "Hey Roisin, your intelligence is inspiring.",
    "Rolo, your talent is a special gift.",
    "Hey Roisin, your beauty is timeless.",
    "Rolo, your kindness is so comforting.",
    "Hey Roisin, your intelligence is a guide.",
    "Rolo, your talent is truly marvelous.",
    "Hey Roisin, your beauty is enchanting.",
    "Rolo, your kindness makes a difference.",
    "Hey Roisin, your intelligence shines.",
    "Rolo, your talent is a marvel.",
    "Hey Roisin, your beauty is captivating.",
    "Hey Roisin, you're so pretty, and your beauty is both inside and out, just like your beautifully designed creations.",
    "Rolo, your kindness is a beacon of light and a blessing that makes the world a better place, both in and out of the classroom.",
    "Hey Roisin, you're super smart, navigating the world of technology and education with brilliance.",
    "Rolo, your talent is amazing and adds a special touch to everything you do, be it woodwork or crafting circuits.",
    "Hey Roisin, your beauty is truly timeless and captivating, like the elegance of your design concepts.",
    "Rolo, your kindness is heartwarming and a gift that keeps on giving, creating a positive atmosphere in every tech venture.",
    "Hey Roisin, you're truly beautiful, and your beauty is a timeless and captivating charm, just like your teaching style.",
    "Rolo, your intelligence is inspiring, both in the world of technology and as an educator shaping young minds.",
    "Hey Roisin, your talent is incredible and a true marvel, just like the amazing projects you guide your students to create.",
    "Rolo, your beauty is enchanting and captivating, leaving a lasting impression like a beautifully crafted piece of technology.",
    "Hey Roisin, you're kind and wonderful, truly inspiring both as a teacher and a tech enthusiast.",
    "Rolo, your intelligence is a guide and a beacon of wisdom, lighting the path in both the world of tech and education.",
    "Hey Roisin, your talent is a marvelous and unique blessing, whether it's in the workshop or the tech lab.",
    "Rolo, yer tech-savvy ways are like a dander through the digital domain—confident, savvy, and absolutely sound.",
    "Hey Roisin, as a tech maestro, yer intelligence is like a grand bit of craic—structured and class.",
    "Rolo, yer gift for teachin' technology is like a maestro orchestratin' a symphony of learnin', absolutely class.",
    "Hey Roisin, yer beauty shines brighter than Divis Mountain on a clear day—pure breathtaking.",
    "Rolo, yer kindness in the classroom is like a cup of tea on a cold Belfast day—warm, comforting, and a real tonic.",
    "Hey Roisin, as an Irish educator, yer intelligence is as sturdy as the Peace Bridge, bridgin' the gaps in knowledge.",
    "Rolo, yer teachin' style is like a session in Kelly's Cellars—full of life, full of stories, and absolutely unforgettable.",
    "Hey Roisin, yer beauty is like a mural on the Peace Wall—captivatin', powerful, and full of character.",
    "Rolo, yer kindness is like a Belfast 'wee smile'—small, genuine, and spreadin' joy wherever it goes.",
    "Hey Roisin, as a tech teacher, yer intelligence is like a Belfast taxi driver—knows all the routes to success.",
    "Rolo, yer talent for teachin' technology is like a pint of the black stuff—smooth, rich, and a taste of brilliance.",
    "Hey Roisin, yer beauty is like a stroll along the River Lagan—serene, timeless, and utterly lovely.",
    "Rolo, yer kindness in the classroom is like a Belfast 'wee dander'—a leisurely walk through knowledge with a friendly vibe.",
    "Hey Roisin, as an Irish educator, yer intelligence is as resilient as the H&W cranes, buildin' a foundation of knowledge.",
    "Rolo, yer teachin' talent is like a set of lambeg drums—powerful, rhythmic, and leavin' an impact.",
    "Hey Rolo, in the technology classroom, yer intelligence is like a GPS for learnin', guidin' students through the digital maze.",
    "Rolo, yer talent for teachin' technology is like a trad session in the Duke of York—full of energy and absolutely brilliant.",
    "Hey Roisin, yer beauty is like the Giant's Causeway—unique, awe-inspiring, and a natural wonder.",
    "Rolo, yer kindness is like a Belfast welcome—open, friendly, and makin' everyone feel at home.",
    "Hey Roisin, as a tech teacher, yer intelligence is like a Belfast wit—sharp, clever, and always on point.",
    "Rolo, yer teachin' talent is like an Ulster Fry—fillin', satisfying, and a hearty portion of wisdom.",
    "Hey Rolo, yer teachin' style is like a quare bit of craic—sharp, clever, and pure inspirin'.",
    "Rolo, yer tech-savvy ways are like a dander through the digital domain—confident, savvy, and absolutely sound.",
    "Hey Roisin, as a tech maestro, yer intelligence is like a grand bit of class—structured and top-notch.",
    "Rolo, yer gift for teachin' technology is like a maestro orchestratin' a symphony of learnin', absolutely class.",
    "Hey Roisin, yer beauty shines brighter than the Sperrins on a sunny day—pure breathtaking.",
    "Rolo, yer kindness in the classroom is like a cup of Coffee from Milano Cafe, warm, comforting, and a real tonic.",
    "Hey Roisin, as a local educator, yer intelligence is as sturdy as the Bridge Street Bridge, bridgin' the gaps in knowledge.",
    "Rolo, yer teachin' style is like a session in the Fir Trees Hotel,full of life, full of stories, and absolutely unforgettable.",
    "Hey Roisin, yer beauty is like a mural on the Derry Road—captivatin', powerful, and full of character.",
    "Rolo, yer kindness is like a Strabane 'wee smile'—small, genuine, and spreadin' joy wherever it goes.",
    "Hey Roisin, as a tech teacher, yer intelligence is like a local taxi driver—knows all the routes to success.",
    "Rolo, yer talent for teachin' technology is like a pint from Charlies's—smooth, rich, and a taste of brilliance.",
    "Hey Roisin, yer beauty is like a walk along the River Mourne—serene, timeless, and utterly lovely.",
    "Rolo, yer kindness in the classroom is like a Strabane 'wee dander'—a leisurely walk through knowledge with a friendly vibe.",
    "Rolo, yer teachin' talent is like a set of Lambeg drums in the Alley Theatre—powerful, rhythmic, and leavin' an impact.",
    "Hey Rolo, in the technology classroom, yer intelligence is like a GPS for learnin', guidin' students through the digital maze.",
    "Rolo, yer talent for teachin' technology is like a trad session in Christys's Bar—full of energy and absolutely brilliant.",
    "Hey Roisin, yer beauty is like the Mourne Valley—unique, awe-inspiring, and a natural wonder.",
    "Rolo, yer kindness is like a Strabane welcome—open, friendly, and makin' everyone feel at home.",
    "Hey Roisin, as a tech teacher, yer intelligence is like a Strabane wit—sharp, clever, and always on point.",
    "Roisin, your authenticity is a breath of fresh air in a world that sometimes feels too polished.",
    "You have this incredible ability to make people feel heard and understood, Roisin.",
    "Rolo, your down-to-earth nature makes you incredibly approachable and easy to connect with.",
    "Roisin, your sense of humor is like a hidden gem that never fails to brighten my day.",
    "Rolo, you navigate life with such grace and resilience, and it's truly inspiring.",
    "Roisin, your straightforward honesty is one of your most admirable qualities.",
    "Rolo, you bring a sense of calm and stability wherever you go.",
    "Roisin, your kindness is not just a gesture; it's a genuine part of who you are.",
    "Rolo, your ability to find joy in the little things is contagious and uplifting.",
    "Roisin, your grounded perspective is a guiding light in a world that can be overwhelming.",
    "Rolo, your strength is not just physical; it's the quiet resilience that defines you.",
    "Roisin, you have this innate ability to make everyone around you feel valued and appreciated.",
    "Rolo, your humility is a rare and beautiful quality that sets you apart.",
    "Roisin, your practical wisdom is something I truly admire; you have a knack for making the complex seem simple.",
    "Rolo, your laughter is like a melody that brings joy to any room.",
    "Roisin, your approach to life is refreshingly real and relatable.",
    "Rolo, your warmth and kindness create a welcoming atmosphere wherever you are.",
    "Roisin, you have this incredible knack for turning ordinary moments into extraordinary memories.",
    "Rolo, your presence has a comforting and reassuring effect on those lucky enough to know you.",
    "Roisin, your ability to stay true to yourself is a testament to your inner strength and character.",
    "Roisin, your blue eyes are pure magic.",
    "Rolo, your smile lights up any room.",
    "Roisin, your prettiness is timeless.",
    "Rolo, your long brown hair is stunning.",
    "Roisin, those blue eyes sparkle with charm.",
    "Rolo, your smile is simply contagious.",
    "Roisin, your prettiness is effortlessly captivating.",
    "Rolo, your long brown hair is a beautiful frame.",
    "Roisin, those blue eyes hold so much warmth.",
    "Rolo, your smile is a daily dose of joy.",
    "Roisin, your prettiness is natural elegance.",
    "Rolo, your long brown hair is a gorgeous feature.",
    "Roisin, blue eyes that speak volumes.",
    "Rolo, a smile that brightens every moment.",
    "Roisin, your prettiness is genuine beauty.",
    "Rolo, your long brown hair is a lovely accent.",
    "Roisin, those blue eyes are truly captivating.",
    "Rolo, your smile is a sunshine beam.",
    "Roisin, your blue eyes are like a clear summer sky.",
    "Rolo, your smile is an instant mood-lifter.",
    "Roisin, prettiness that radiates from within.",
    "Rolo, your smile is pure sunshine in human form.",
    "Roisin, the sparkle in your blue eyes is contagious.",
    "Rolo, your smile has the power to light up any day.",
    "Roisin, your prettiness is a natural work of art.",
    "Roisin, blue eyes that captivate with every gaze.",
    "Rolo, your smile is the best accessory you wear.",
    "Roisin, prettiness that stands out in any crowd.",
    "Rolo, your long brown hair is a stunning feature.",
    "Roisin, those blue eyes express kindness and depth.",
    "Rolo, your smile is a beacon of positivity.",
    "Roisin, prettiness that leaves a lasting impression.",
    "Roisin, your sense of style is effortlessly chic.",
    "Rolo, your fashion choices are always on point.",
    "Roisin, you have a unique and captivating style.",
    "Rolo, your wardrobe is a reflection of your vibrant personality.",
    "Roisin, your fashion sense is modern and timeless.",
    "Rolo, you bring an elegant flair to every outfit.",
    "Roisin, your style is a perfect blend of sophistication and comfort.",
    "Rolo, your fashion choices showcase your creativity.",
    "Roisin, you have an eye for stylish details that make every outfit pop.",
    "Rolo, your style is a true expression of individuality.",
    "Roisin, your wardrobe is as versatile as it is stylish.",
    "Rolo, your fashion sense is a source of inspiration.",
    "Roisin, you effortlessly make any outfit look fabulous.",
    "Rolo, your style is both polished and relaxed.",
    "Roisin, your fashion choices exude confidence.",
    "Rolo, you have a knack for putting together the perfect ensemble.",
    "Roisin, your style is a reflection of your impeccable taste.",
    "Rolo, you bring a touch of glamour to everyday fashion.",
    "Roisin, your outfits are a work of art.",
    "Rolo, your style is a statement of individuality and grace.",
    "Roisin, if beauty were time, you would be an eternity.",
    "Rolo, your charm is so contagious, even vaccines are jealous.",
    "Roisin, you're so stylish, even your shadow can't keep up.",
    "Rolo, if laughter is the best medicine, your smile must be a pharmacy.",
    "Roisin, you're not a snack; you're the whole picnic.",
    "Rolo, your personality is so magnetic, even mirrors can't resist reflecting it.",
    "Roisin, if sass were a sport, you'd be a world champion.",
    "Rolo, if there were a trophy for being witty, you'd have a shelf full.",
    "Roisin, you're not just a pretty face; you're a hilarious masterpiece.",
    "Rolo, your confidence is so high, it's doing the limbo under the moon.",
    "Roisin, you're so funny, even your jokes have dad jokes rolling on the floor.",
    "Rolo, if life were a comedy show, you'd be the headliner.",
    "Roisin, your sass levels are on par with a cat meme ,off the charts.",
    "Roisin, you're like a cupcake in a world of muffins , sweet, with a sprinkle of sass.",
    "Rolo, your humor is sharper than a brand new pencil.",
    "Roisin, if sarcasm were an Olympic sport, you'd be a gold medalist.",
    "Rolo, your wit is so quick, it outruns the punchline.",
    "Roisin, if looks could kill, you'd be a weapon of mass seduction.",
    "Rolo, your confidence is so high, even birds are looking up to you.",
    "Roisin, your sense of style makes the fashion world jealous.",
    "Rolo, you're not just cool; you're an absolute chill-out masterpiece.",
    "Roisin, if attitude were a currency, you'd be a millionaire.",
    "Rolo, your charisma is so magnetic; you could power a city.",
    "Roisin, if sarcasm were an Olympic sport, you'd have a gold medal.",
    "Rolo, your wit is sharper than a chef's knife in a cooking show.",
    "Roisin, your sass levels are a force to be reckoned with.",
    "Rolo, your charm is so effortless; it's like breathing for you.",
    "Roisin, if laughter were a crime, you'd be a repeat offender.",
    "Rolo, your walk is like a runway show , fierce and fabulous.",
    "Roisin, your confidence is so high; it's doing acrobatics.",
    "Rolo, if coolness were a temperature, you'd be absolute zero.",
    "Roisin, your presence alone is a statement , bold and unforgettable.",
    "Rolo, you're not just a trendsetter; you're a trend creator.",
    "Roisin, if there were an award for eye-rolling, you'd be a Hall of Famer.",
    "Rolo, your comeback game is so strong; it's on the next level.",
    "Roisin, if charisma were a perfume, you'd be the best-selling fragrance.",
    "Rolo, your confidence could outshine a spotlight.",
    "Roisin, if coolness were an art form, you'd be a masterpiece.",
    "Rolo, your attitude is so on point; it deserves its own fan club.",
    "Roisin, your style is so cutting-edge; it could slice through trends effortlessly.",
    "Rolo, your charisma is like a spotlight; it shines on you wherever you go.",
    "Roisin, if confidence were a language, you'd be fluent in it.",
    "Rolo, your swagger is so authentic; it should be patented.",
    "Roisin, if there were a championship for being fabulous, you'd be the reigning queen.",
    "Rolo, your level of charm is on par with a Hollywood heartthrob.",
    "Roisin, if there were a diploma for being sassy, you'd have a Ph.D.",
    "Rolo, your cool factor is off the charts; even thermometers are jealous.",
    "Roisin, if there were an award for eye-rolling, you'd win it without breaking a sweat.",
    "Rolo, your sense of humor is so sharp; it could cut through any dull moment.",
    "Roisin, your confidence is so high; it's practically in the stratosphere.",
    "Rolo, your wit is like a fine wine; it gets better with every clever remark.",
    "Roisin, if there were a reality show about being fabulous, you'd be the star.",
    "Rolo, your presence is like a cool breeze on a hot summer day , refreshing and welcome.",
    "Roisin, if there were a throne for the queen of sass, you'd be sitting on it.",
    "Roisin, if confidence were a superpower, you'd be a superhero.",
    "Rolo, your charm is so potent; it's practically a magic spell.",



    ];

    var myButton = document.getElementById('myButton');
    var displayText = document.getElementById('displayText');

    myButton.addEventListener('click', function() {
        // Get a random compliment from the array
        var randomIndex = Math.floor(Math.random() * compliments.length);
        var randomCompliment = compliments[randomIndex];

        // Display the compliment
        displayText.textContent = randomCompliment;
    });
});

